create database qlcf1
go
use qlcf1
go

IF OBJECT_ID('NHANVIEN') IS NOT NULL
DROP TABLE NHANVIEN
GO
CREATE TABLE NHANVIEN (
	MANV VARCHAR(10) NOT NULL,
	TENNV NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	SDT VARCHAR(15) NOT NULL,
	CALAM BIT NOT NULL,
	LUONGCB INT,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
	)
IF OBJECT_ID('TAIKHOAN') IS NOT NULL
DROP TABLE TAIKHOAN
GO
CREATE TABLE TAIKHOAN (
	IDNV VARCHAR(10) NOT NULL,
	MATKHAU VARCHAR(30) NOT NULL,
	VAITRO BIT DEFAULT 0,
	MANV VARCHAR(10) NOT NULL,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (IDNV),
	CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN
	)
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG(
	MAKH INT IDENTITY(1,1),
	TENKH NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	SDT VARCHAR(15) NOT NULL,
	DIEM FLOAT,
	MANV VARCHAR(10) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
	CONSTRAINT FK_KHACHHANG_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN
	)

IF OBJECT_ID('SANPHAM') IS NOT NULL
DROP TABLE SANPHAM
GO
CREATE TABLE SANPHAM (
	MASP VARCHAR(10) NOT NULL,
	TENSP NVARCHAR(50)NOT NULL,
	GIA FLOAT NOT NULL,
	HINHANH nvarchar(50) ,
	MANV VARCHAR(10)NOT NULL,
	CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP),
	CONSTRAINT FK_SANPHAM_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN
	)

IF OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON
GO
CREATE TABLE HOADON (
	MAHD INT IDENTITY(1,1),
	TONGTIEN FLOAT NOT NULL,
	MAKH INT NOT NULL,
	IDNV VARCHAR(10) NOT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
	CONSTRAINT FK_HOADON_TAIKHOAN FOREIGN KEY(IDNV) REFERENCES TAIKHOAN,
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG
	)
	IF OBJECT_ID('HOADONCHITIET') IS NOT NULL
DROP TABLE HOADONCHITIET
GO
CREATE TABLE HOADONCHITIET (
	MASP VARCHAR(10) NOT NULL,
	MAHD INT not null,
	TONGTIEN FLOAT NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYTAO DATE DEFAULT GETDATE(),
	CONSTRAINT PK_HOADONCHITIET PRIMARY KEY (MAHD,MASP),
	CONSTRAINT FK_HOADONCHITIET_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM,
	CONSTRAINT FK_HOADONCHITIET_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON
	)
	select *from hoadon
	select *from TAIKHOAN
	select *from NHANVIEN
	select *from HOADONCHITIET
	select *from khachhang
	