/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDI;

import helper.Auth;
import helper.JDialogHelper;
import java.util.List;
import javax.print.attribute.standard.DateTimeAtCompleted;
import javax.swing.DefaultComboBoxModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import landCoffee_DAO.HoaDonChiTiet_DAO;
import landCoffee_DAO.HoaDon_DAO;
import landCoffee_DAO.KhachHang_DAO;
import landCoffee_DAO.SanPham_DAO;
import landCoffee_Entity.HoaDon;
import landCoffee_Entity.HoaDonChiTiet;
import landCoffee_Entity.KhachHang;
import landCoffee_Entity.SanPham;
import java.sql.Date;
import java.time.LocalDate;

/**
 *
 * @author Dell
 */
public class BanHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrangChu
     */
    DefaultTableModel mol;
    float tongTien;
    SanPham_DAO daoSP = new SanPham_DAO();
    HoaDon_DAO hdDAO = new HoaDon_DAO();
    HoaDonChiTiet_DAO hdctDAO = new HoaDonChiTiet_DAO();
    KhachHang_DAO khDAO = new KhachHang_DAO();
    boolean checkRow = false;
    int count = 0;
    int maHD = 1;
    int maKH;
    String maKH1;
    boolean thanhToanLuon = false;

    public BanHang() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboMenu = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        txtSL = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTienTraLai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cbodiscout = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Đơn Giá", "Số Lượng", "Tổng Tiền"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel15.setText("Số lượng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Trang Chủ");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cafe_1.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cafe sữa1.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nước cam1.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trà sữa 1.png"))); // NOI18N
        jLabel14.setText("jLabel9");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cboMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(58, 58, 58)
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Đồ uống", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("", jPanel5);

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Đơn Giá", "Số Lượng"
            }
        ));
        tblBang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblBangKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblBang);

        txtSL.setText("1");
        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Số lượng");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add to basket.png"))); // NOI18N
        jButton5.setText("Thêm đồ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        jButton6.setText("Bỏ đồ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Thành Tiền");

        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tiền Khách Đưa");

        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyTyped(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tiền Trả Lại");

        txtTienTraLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienTraLaiActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save as.png"))); // NOI18N
        jButton1.setText("Tạo hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã khách hàng");

        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save as.png"))); // NOI18N
        jButton2.setText("Thanh toán");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ghi chú");

        cbodiscout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbodiscout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodiscoutActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGhiChu))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton3)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTienTraLai)
                            .addComponent(txtTongTien)
                            .addComponent(txtTienKhachDua)
                            .addComponent(txtMaKH))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbodiscout, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(94, 94, 94))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtTienTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbodiscout))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTienTraLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienTraLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienTraLaiActionPerformed

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        fillTable();
        checkRow = true;
        System.out.println(count);
        txtTongTien.setText(tongTien + "");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (tblBang.getSelectedRow() >= 0) {
            tongTien = tongTien - Float.parseFloat(tblBang.getValueAt(tblBang.getSelectedRow(), 3) + "");

            txtTongTien.setText(tongTien + "");
            boDo();
            count--;
        } else {
            JDialogHelper.alert(this, "Chưa chọn đồ cần bỏ");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtTienKhachDuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTienKhachDuaKeyPressed

    private void txtTienKhachDuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTienKhachDuaKeyTyped

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        // TODO add your handling code here:
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienTraLai.setText("");
        }
        tinhTienTraLai();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (count == 0) {
            JDialogHelper.alert(this, "Chưa thêm đồ uống");
        }
        checkMaKH();
        if (checkMaKH() == true && count != 0) {
            themHD();
            List<HoaDon> list = hdDAO.selectAll();
            int x = list.size();
            maHD = list.get(x - 1).getMaHD();
            System.out.println(maHD);
            for (int xy = 0; xy < count; xy++) {
                int sl = Integer.parseInt(tblBang.getValueAt(xy, 1) + "");
                themHDCT(xy, sl);
            }
            JDialogHelper.alert(this, "Tạo hóa đơn thành công");
        }

        // themHDCT();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        thanhToanLuon = true;
        if (count == 0) {
            JDialogHelper.alert(this, "Chưa thêm đồ uống");
        }
        checkMaKH();
        if (checkMaKH() == true && count != 0) {
            themHD();
            List<HoaDon> list = hdDAO.selectAll();
            int x = list.size();
            maHD = list.get(x - 1).getMaHD();
            System.out.println(maHD);
            for (int xy = 0; xy < count; xy++) {
                int sl = Integer.parseInt(tblBang.getValueAt(xy, 1) + "");
                themHDCT(xy, sl);
            }
            JDialogHelper.alert(this, "Thanh toán thành công");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblBangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBangKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tblBangKeyReleased

    private void cbodiscoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodiscoutActionPerformed
        // TODO add your handling code here:
        if (cbodiscout.getSelectedIndex() > 0) {
            if (txtTongTien.getText().isEmpty() == false) {
                String voucher = cbodiscout.getSelectedItem() + "";//20%
                int getIndexByVoucher = voucher.indexOf("%");
                float _voucher = 1 - ((Float.parseFloat(voucher.substring(0, getIndexByVoucher)) / 100));
                System.out.println("voucher " + _voucher);
                float tongTienUpdate = tongTien * _voucher;
                txtTongTien.setText(tongTienUpdate + "");

            }
        }
    }//GEN-LAST:event_cbodiscoutActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
        System.out.println(txtTongTien.getText());
    }//GEN-LAST:event_jButton3ActionPerformed
    void init() {
        setTable();
        setCBO();
        setCBO1();
        txtTienTraLai.setEnabled(false);
    }

    void setCBO1() {
        DefaultComboBoxModel mol = (DefaultComboBoxModel) cbodiscout.getModel();
        mol.removeAllElements();
        mol.addElement("Chọn Voucher");
        mol.addElement("0%");
        mol.addElement("10%");
        mol.addElement("20%");
        mol.addElement("30%");
        mol.addElement("40%");
        mol.addElement("50%");
        mol.addElement("60%");
        mol.addElement("70%");
        mol.addElement("80%");
        mol.addElement("90%");
        mol.addElement("100%");
    }

    void setTable() {
        mol = (DefaultTableModel) tblBang.getModel();
        mol.setColumnCount(0);
        String col[] = {" Tên Sản phẩm", "Số lượng", "Giá tiền", "Thành tiền", "Ghi chú"};
        for (String x : col) {
            mol.addColumn(x);
        }
    }

    void setCBO() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMenu.getModel();
        model.removeAllElements();
        List<SanPham> list = daoSP.selectAll();
        for (SanPham x : list) {
            model.addElement(x);
        }

    }

    boolean checkMaKH() {
        if (txtMaKH.getText().equalsIgnoreCase("")) {
            return true;
        }
        try {
            maKH = Integer.parseInt(txtMaKH.getText() + "");
        } catch (Exception e) {
            JDialogHelper.alert(this, "Mã khách hàng phải là 1 số");
            txtMaKH.requestFocus();
            return false;
        }
        KhachHang list = khDAO.selectById(txtMaKH.getText() + "");

        if (list != null) {
            return true;
        } else {
            JDialogHelper.alert(this, "Không tìm thấy mã khách hàng");
            txtMaKH.requestFocus();
            return false;
        }
    }

    HoaDon getForm() {
        try {
            Integer.parseInt(txtMaKH.getText() + "");
            String maKH = txtMaKH.getText();
            Float.parseFloat(txtTongTien.getText() + "");
            tongTien = Float.parseFloat(txtTongTien.getText() + "");
            System.out.println(txtTongTien.getText());
        } catch (Exception e) {
            System.out.println("LỖi tt");
        }
        tongTien = Float.parseFloat(txtTongTien.getText() + "");
        if (txtMaKH.getText().equalsIgnoreCase("")) {
            return new HoaDon("1", Auth.user.getTaiKhoan(), tongTien, thanhToanLuon);
        } else {
            return new HoaDon(txtMaKH.getText(), Auth.user.getTaiKhoan(), tongTien, thanhToanLuon);
        }

    }

    void themHD() {
        try {
            HoaDon hd = getForm();
            hdDAO.insert(hd);
            JDialogHelper.alert(this, "Thêm thành công");

        } catch (Exception e) {
            JDialogHelper.alert(this, "Lỗi");
        }
    }

    void themHDCT(int rowSel, int SL
    ) {
        try {
            HoaDonChiTiet hdct = getForm1(rowSel, SL);
            hdctDAO.insert(hdct);
            // JDialogHelper.alert(this, "Thêm thành công");
        } catch (Exception e) {
            JDialogHelper.alert(this, "Thêm thất bại");
        }
    }

    HoaDonChiTiet getForm1(int rowSel, int SL
    ) {

        List<SanPham> list = daoSP.selectAll();
        Date date = Date.valueOf(LocalDate.now());
        double gia = 0;
        String maSP = "";
        for (SanPham x : list) {
            if (x.getTenSP().equalsIgnoreCase(tblBang.getValueAt(rowSel, 0) + "")) {
                gia = x.getGia();
                maSP = x.getMaSP();
                System.out.println(gia);
                break;
            }
        }
        HoaDonChiTiet hdct = new HoaDonChiTiet(maSP, SL, maHD, tongTien, date, txtGhiChu.getText());
        return hdct;
    }

    void fillTable() {
        List<SanPham> list = daoSP.selectAll();
        double gia = 0;
        String tenSP = "";
        boolean checkTrungSP = false;
        for (SanPham x : list) {
            if (x.getTenSP().equalsIgnoreCase(cboMenu.getSelectedItem() + "")) {
                gia = x.getGia();
                tenSP = x.getTenSP();
                break;
            }
        }
        Integer sl = Integer.parseInt(txtSL.getText());
        if (sl < 0) {
            JDialogHelper.alert(this, "Số lượng phải lớn hơn 0");
            return;
        }
        double thanhTien = sl * gia;
        tongTien = (float) (tongTien + thanhTien);
        DefaultTableModel mol = (DefaultTableModel) tblBang.getModel();
        String ghiChu = txtGhiChu.getText();
        Object[] row = {cboMenu.getSelectedItem(), txtSL.getText(), gia, thanhTien, ghiChu};
        if (count > 0) {
            for (int x = 0; x < count; x++) {
                if (cboMenu.getSelectedItem().equals(tblBang.getValueAt(x, 0))) {
                    int sl1 = sl + Integer.parseInt(tblBang.getValueAt(x, 1) + "");
                    double thanhTien1 = thanhTien + Double.parseDouble(tblBang.getValueAt(x, 3) + "");
                    mol.setValueAt(sl1, x, 1);
                    mol.setValueAt(ghiChu, x, 4);
                    mol.setValueAt(thanhTien1, x, 3);
                    checkTrungSP = false;
                    break;
                } else {
                    checkTrungSP = true;
                }
            }

        } else {
            mol.addRow(row);
            count++;
        }
        if (checkTrungSP == true) {
            mol.addRow(row);
            count++;
        }
    }

    void boDo() {
        DefaultTableModel mol = (DefaultTableModel) tblBang.getModel();
        mol.removeRow(tblBang.getSelectedRow());
    }

    void tinhTienTraLai() {
        float tienTraLai;
        try {
            float tienKhachDua = Float.parseFloat(txtTienKhachDua.getText() + "");
            float tienTong = Float.parseFloat(txtTongTien.getText() + "");
            tienTraLai = tienKhachDua - tienTong;
            if (txtTienKhachDua.getText().equalsIgnoreCase("")) {
                txtTienTraLai.setText("");
            } else {
                txtTienTraLai.setText(tienTraLai + "");
            }
        } catch (Exception e) {
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMenu;
    private javax.swing.JComboBox<String> cbodiscout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienTraLai;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
