/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDI;

import java.text.DecimalFormat;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import landCoffee_DAO.HoaDonChiTiet_DAO;
import landCoffee_Entity.HoaDonChiTiet;

/**
 *
 * @author Dell
 */
public class ThongKe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKe
     */
    private List<HoaDonChiTiet> hdchitiet;
    private DefaultTableModel mol;

    public ThongKe() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        mol = (DefaultTableModel) tblThongKe.getModel();
        showTable();
        TongDoanhThu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jLabelTong = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnserach = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Tạo", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblThongKe);

        jLabelTong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTong.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTong.setText("Tổng doanh thu:");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        btnserach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnserach.setText("Search");
        btnserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserachActionPerformed(evt);
            }
        });

        btnRefesh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefesh.setText("Refesh");
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTong, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnserach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDate)
                    .addComponent(btnserach, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnRefesh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabelTong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDateActionPerformed

    private void btnserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserachActionPerformed
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_btnserachActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        // TODO add your handling code here:\
        txtDate.setText("");
        showTable();
    }//GEN-LAST:event_btnRefeshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnserach;
    private javax.swing.JLabel jLabelTong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables

    HoaDonChiTiet_DAO dao = new HoaDonChiTiet_DAO();

    private void showTable() {
        hdchitiet = new HoaDonChiTiet_DAO().selectAll();
        mol.setRowCount(0);
        for (int x = 0; x < hdchitiet.size(); x++) {
            if (x > 0 && hdchitiet.get(x).getMaHD() == hdchitiet.get(x - 1).getMaHD()) {
                continue;
            }
            mol.addRow(new Object[]{hdchitiet.get(x).getMaHD(), hdchitiet.get(x).getNgayTao(), hdchitiet.get(x).getTongTien()});
        }
    }

    private void TongDoanhThu() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        float tong = 0;
        for (int i = 0; i < tblThongKe.getRowCount(); i++) {
            tong += Float.parseFloat(tblThongKe.getValueAt(i, 2).toString());
            jLabelTong.setText("Tổng doanh thu : " + x.format(tong) + " " + "VND");
        }
    }

    void find() {
        DefaultTableModel model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        String keyword = txtDate.getText();
        List<HoaDonChiTiet> list = dao.selectByKeyword(keyword);
        for (int x = 0; x < list.size(); x++) {
            if (x > 0 && list.get(x).getMaHD() == list.get(x - 1).getMaHD()) {
                continue;
            }
            mol.addRow(new Object[]{list.get(x).getMaHD(), list.get(x).getNgayTao(), list.get(x).getTongTien()});
        }
    }

}
